# Generated by Django 5.2.1 on 2025-06-10 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_login_attempt',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('camera', models.ManyToManyField(blank=True, to='media.camera')),
                ('lens', models.ManyToManyField(blank=True, to='media.lens')),
            ],
        ),
    ]
