# Generated by Django 5.2.1 on 2025-06-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_session_expire_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
    ]
