# Generated by Django 5.2.1 on 2025-06-02 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('display_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('created_At', models.DateField(db_default=datetime.datetime(2025, 6, 2, 19, 52, 45, 228144))),
            ],
        ),
    ]
