# Generated by Django 5.2.1 on 2025-06-07 02:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2025, 6, 14, 2, 21, 34, 124017, tzinfo=datetime.timezone.utc))),
                ('login_attempts', models.SmallIntegerField(default=0)),
                ('last_login_attempt', models.DateTimeField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
