# Generated by Django 5.2.1 on 2025-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_at',
            field=models.DateTimeField(),
        ),
    ]
