# Generated by Django 5.2.1 on 2025-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_session_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='last_login_attempt',
            field=models.DateTimeField(null=True),
        ),
    ]
