# Generated by Django 5.2.1 on 2025-06-05 19:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_make', models.CharField(max_length=25)),
                ('camera_model', models.CharField(db_index=True, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lens_model', models.CharField(db_index=True, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/')),
                ('location', django.contrib.gis.db.models.fields.MultiPointField(blank=True, geography=True, srid=4326)),
                ('f_stop', models.CharField(max_length=25, null=True)),
                ('ISO', models.IntegerField(null=True)),
                ('shutter_speed', models.CharField(max_length=10, null=True)),
                ('focal_length', models.IntegerField(null=True)),
                ('aperture', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('flash', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.camera')),
                ('lens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.lens')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
