# Generated by Django 5.2.1 on 2025-06-10 16:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, srid=4326),
        ),
    ]
