# Generated by Django 5.2.1 on 2025-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(null=True),
        ),
    ]
