# Generated by Django 5.2.1 on 2025-06-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_photo_taken_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='aperture',
        ),
    ]
