# Generated by Django 5.2.1 on 2025-06-12 01:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_photo_aperture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
