# Generated by Django 5.2.1 on 2025-06-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_user_id_photo_user_alter_photo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='camera_make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='camera_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='lens',
            old_name='lens_model',
            new_name='model',
        ),
    ]
