# Generated by Django 5.2.1 on 2025-07-19 18:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_rename_camera_make_camera_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
